/* Automatically generated by configure */
#ifndef GF_CONFIG_H
#define GF_CONFIG_H
#define GPAC_CONFIGURATION ""
#define GPAC_CONFIG_LINUX
#define GPAC_HAS_JPEG
#define GPAC_HAS_PNG
#define GPAC_HAS_LZMA
#define GPAC_HAS_SSL
#define GPAC_HAS_IPV6
#define GPAC_64_BITS
#define GPAC_HAS_LINUX_DVB
#endif
